---
- name: Creates directory for backend
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy and unarchive artifact files
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Start the app
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start