---
- name: Copy and unarchive artifact files
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: Start the app
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm -- start