---
- name: Creates directory for backend
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy and unarchive artifact files
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend

# - name: Start the app
#   shell: |
#     cd /home/ubuntu/backend
#     npm install
#     pm2 stop default
#     pm2 start npm
#     pm2 start ./dist/main.js

- name: install node modules
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: build app
  shell: |
    cd /home/ubuntu/backend
    npm run build
    npm run prestart:prod

- name: run migrations
  shell: |
    cd /home/ubuntu/backend
    npm run migrations

- name: Start the app
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 stop default
    pm2 start npm