---
- name: Copy and unarchive artifact files
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: check files
  shell: |
    cd /home/ubuntu/backend
    ls

- name: Start the app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start